prompt:
I have the following count table for an RNA-seq experiment, rows are genes and columns are samples, "Supplementary_Table_1_exp.xlsx". The first column of the file is my gene names and the rest of the columns are samples. My annotation data is here  "SRP021193.colData.tsv", it contains sample annotations and rows of this matches the columns of count table, first column is the sample ids. Normalize counts, make two PCA plots for samples, one color coded samples by "group" and the other color coded by "LibrarySelection" in my annotation data.

here are first few lines of the file(s).

Supplementary_Table_1_exp.xlsx:
Genes	CASE_1	CASE_2	CASE_3	CASE_4	CASE_5	CASE_6	CTRL_1	CTRL_2	CTRL_3	CTRL_4	CTRL_5	CTRL_6
TSPAN6	9832	25521	23529	0	32	0	10558	20573	6507	0	0	 0
TNMD	3281	 7167	 3435	0	 0	0	  202	  403	 203	0	0	21


SRP021193.colData.tsv:
diagnosis	group	LibrarySelection
CASE_1	non-ischemic cardiomyopathy	CASE	cDNA


response:
My apologies. The error suggests that the column names of the count data matrix don't match with the row names of the column data. Let's make sure to adjust the column names to match the sample names in the column data.

Also, it seems I made an mistake on the column dropping from data frame. `count_data <- count_data[-1]` should have been `count_data <- count_data[,-1]` 

Here's the corrected code:

```
# Libraries needed
if (!requireNamespace("BiocManager", quietly = TRUE))
    
BiocManager::install("DESeq2")
library(DESeq2)

library(readxl)
library(ggplot2)
library(FactoMineR)

# Load data
count_data <- read_excel("Supplementary_Table_1_exp.xlsx")
col_data <- read.table("SRP021193.colData.tsv", sep = "\t", header = TRUE, stringsAsFactors = FALSE)

# Rename duplicate genes by appending a numeric suffix
duplicated_genes <- which(duplicated(count_data$Genes))
count_data$Genes[duplicated_genes] <- paste(count_data$Genes[duplicated_genes], "_dupe", seq_along(duplicated_genes), sep = "")

# Prepare the data for DESeq2
rownames(count_data) <- count_data$Genes
count_data <- count_data[,-1]
# Rename column of count_data to match col_data
colnames(count_data) <- gsub("_", ".", gsub("CTRL", "control", gsub("CASE", "case", colnames(count_data))), fixed = TRUE)
dds <- DESeqDataSetFromMatrix(countData = count_data,
                               colData =  col_data,
                               design = ~ group)

# Normalize the data
dds <- DESeq(dds)
normalized_counts <- counts(dds, normalized = TRUE)

# Perform PCA
pca_res <- prcomp(t(normalized_counts))

# Plot PCA with group annotations
ggplot(pca_res$x, aes(x = PC1, y = PC2, color = col_data$group)) +
  geom_point() +
  xlab(paste("PC1: ", round(pca_res$sdev[1], 2), "% variance")) +
  ylab(paste("PC2: ", round(pca_res$sdev[2], 2), "% variance")) +
  ggtitle("PCA plot color coded by group") +
  theme_classic()

# Plot PCA with LibrarySelection annotations
ggplot(pca_res$x, aes(x = PC1, y = PC2, color = col_data$LibrarySelection)) +
  geom_point() +
  xlab(paste("PC1: ", round(pca_res$sdev[1], 2), "% variance")) +
  ylab(paste("PC2: ", round(pca_res$sdev[2], 2), "% variance")) +
  ggtitle("PCA plot color coded by LibrarySelection") +
  theme_classic()
```  

Please replace the file name with your local file path.
