prompt:
I have the following count table for an RNA-seq experiment, rows are genes and columns are samples, "Supplementary_Table_1_exp.xlsx". The first column of the file is my gene names and the rest of the columns are samples. My annotation data is here  "SRP021193.colData.tsv", it contains sample annotations and rows of this matches the columns of count table, first column is the sample ids. Normalize counts, make two PCA plots for samples, one color coded samples by "group" and the other color coded by "LibrarySelection" in my annotation data.

here are first few lines of the file(s).

Supplementary_Table_1_exp.xlsx:
Genes	CASE_1	CASE_2	CASE_3	CASE_4	CASE_5	CASE_6	CTRL_1	CTRL_2	CTRL_3	CTRL_4	CTRL_5	CTRL_6
TSPAN6	9832	25521	23529	0	32	0	10558	20573	6507	0	0	 0
TNMD	3281	 7167	 3435	0	 0	0	  202	  403	 203	0	0	21


SRP021193.colData.tsv:
diagnosis	group	LibrarySelection
CASE_1	non-ischemic cardiomyopathy	CASE	cDNA


response:
Yeah, you are right. The sample names in your count data do not match those in your annotation data. This is common as the sample names in count data are often a little different from those in the annotation file. Better to match the row names of the annotation file. Then we can set the row names using the sample names in your annotation file.

Please run the code below.

```
# Import the required libraries
library("DESeq2")
library("tidyverse")
library("readxl")

# Read the data
countdata <- readxl::read_excel("Supplementary_Table_1_exp.xlsx")

# Read colData, set rownames to the sample diaganosis
coldata <- read.delim("SRP021193.colData.tsv", header = TRUE, stringsAsFactors = FALSE, row.names = 1)

# make sure that the columns in countdata corresponds to the rows in colData
countdata <- countdata[,c(1,match(rownames(coldata), colnames(countdata)[-1])+1)]

# Create a DESeq data set
dds <- DESeqDataSetFromMatrix(countData = countdata[,-1], 
                              colData = coldata, 
                              design = ~ group)
                              
# Perform DESeq normalization
dds <- DESeq(dds)

rld <- rlog(dds)

# Create PCA plots
pcaData <- plotPCA(rld, intgroup=c("group"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
p1 <- ggplot(pcaData, aes(x=PC1, y=PC2, color=group)) +
  geom_point(size=3) +
  theme_bw() +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance"))
print(p1)

pcaData <- plotPCA(rld, intgroup=c("LibrarySelection"), returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
p2 <- ggplot(pcaData, aes(x=PC1, y=PC2, color=LibrarySelection)) +
  geom_point(size=3) +
  theme_bw() +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance"))
print(p2)
```
