prompt:
I have the following count table for an RNA-seq experiment, rows are genes and columns are samples, "Supplementary_Table_1_exp.xlsx". The first column of the file is my gene names and the rest of the columns are samples. My annotation data is here  "SRP021193.colData.tsv", it contains sample annotations and rows of this matches the columns of count table, first column is the sample ids. Read the tables count number of rows and columns for each.

here are first few lines of the file(s).

Supplementary_Table_1_exp.xlsx:
Genes	CASE_1	CASE_2	CASE_3	CASE_4	CASE_5	CASE_6	CTRL_1	CTRL_2	CTRL_3	CTRL_4	CTRL_5	CTRL_6
TSPAN6	9832	25521	23529	0	32	0	10558	20573	6507	0	0	 0
TNMD	3281	 7167	 3435	0	 0	0	  202	  403	 203	0	0	21


SRP021193.colData.tsv:
	diagnosis	group	LibrarySelection
CASE_1	non-ischemic cardiomyopathy	CASE	cDNA


response:
You can use the `read_excel` function from the `readxl` package to read the data from the excel file and `read.table` function to read the data from the tsv file. Then you can check its dimensions using the `dim` function in R as follows. Here is the R code for it.

```
# Load library
library(readxl)

# Read data from excel file
exp_data <- read_excel("Supplementary_Table_1_exp.xlsx")

# Print the number of rows and columns of the data 
print(paste0("Number of rows in exp_data: ", nrow(exp_data)))
print(paste0("Number of columns in exp_data: ", ncol(exp_data)))


# Read data from tsv file
tsv_data <- read.table("SRP021193.colData.tsv", header = TRUE, sep = "\t")

# Print the number of rows and columns of the data 
print(paste0("Number of rows in tsv_data: ", nrow(tsv_data)))
print(paste0("Number of columns in tsv_data: ", ncol(tsv_data)))
```

This code first loads the necessary library, then it reads the data from the excel file and the tsv file. It then prints the number of rows and columns of each data.  Notice how `read.table` specifies a "\t" separator as it is a tsv file (tab separated values).
