prompt:
I have the following gene expression data as an excel sheet,  "Supplementary_Table_1_exp.xlsx". Each row is a gene and each column is a distinct sample. First column contains gene names. How many genes and samples does the dataset have?

here are first few lines of the file(s).

Supplementary_Table_1_exp.xlsx:
Genes	CASE_1	CASE_2	CASE_3	CASE_4	CASE_5	CASE_6	CTRL_1	CTRL_2	CTRL_3	CTRL_4	CTRL_5	CTRL_6
TSPAN6	9832	25521	23529	0	32	0	10558	20573	6507	0	0	 0
TNMD	3281	 7167	 3435	0	 0	0	  202	  403	 203	0	0	21


response:
To handle this task, you can use the `readxl` package in R which allows to read data from excel file. Then, the number of rows and columns can be identified using `nrow()` and `ncol()` functions respectively. If the first column contains gene names, the number of samples would be total number of columns minus one.

Here is the R code:

```
# Installing 'readxl' package which is needed to read an Excel file


# Loading 'readxl' package
library(readxl)

# Reading the excel file
data <- read_excel("Supplementary_Table_1_exp.xlsx")

# Print out the dimensions of the dataframe : number of rows (genes) and columns (samples +1)
print(dim(data))

# number of genes
num_genes <- nrow(data)
print(paste("The dataset has", num_genes, "genes"))

# number of samples
num_samples <- ncol(data) -1
print(paste("The dataset has", num_samples, "samples"))
```
You should replace "Supplementary_Table_1_exp.xlsx" with the correct path to your Excel file if it's not in the working directory.
