prompt:
I have the following gene expression data as an excel sheet,  "Supplementary_Table_1_exp.xlsx". Each row is a gene and each column is a distinct sample. First column contains gene names. How many genes and samples does the dataset have?

here are first few lines of the file(s).

Supplementary_Table_1_exp.xlsx:
Genes	CASE_1	CASE_2	CASE_3	CASE_4	CASE_5	CASE_6	CTRL_1	CTRL_2	CTRL_3	CTRL_4	CTRL_5	CTRL_6
TSPAN6	9832	25521	23529	0	32	0	10558	20573	6507	0	0	 0
TNMD	3281	 7167	 3435	0	 0	0	  202	  403	 203	0	0	21


response:
First, you need to install and load the necessary packages to read the Excel file. You can use `readxl` and `tidyverse` packages.

In this example we will use function `read_excel()` from `readxl` package to read the excel file. Then, we use function `dim()` to get the dimensions of the dataset (rows and columns). 

The number of genes is equivalent to the number of rows in the dataset minus 1 (because the first row is reserved for column names), and the number of samples is equivalent to the number of columns minus 1 (because the first column contains gene names).

Here is the R code for this task:
```
# importing required libraries

library(readxl)
library(tidyverse)

# read the excel file
gene_data <- read_excel("Supplementary_Table_1_exp.xlsx")

# get the number of rows and columns
num_rows <- nrow(gene_data) - 1 # subtract 1 to exclude column names
num_cols <- ncol(gene_data) - 1 # subtract 1 to exclude gene names

# print the number of genes and samples
print(paste("The number of genes is ", num_rows))
print(paste("The number of samples is ", num_cols))
```
Please make sure the file "Supplementary_Table_1_exp.xlsx" is in your working directory. You can check and set your current working directory with `getwd()` and `setwd()` functions, respectively.
