prompt:
We have the following datasets. One of the dataset contains CpG methylation values per CpG and per individual as a table this is contained in the “metRmOlWithDbgapIdHeader.txt” file. Each column is an individual represented by a DBGapId, which is included as the first row. Each row is a CpG represented by "CpG_id", values in the table are methylation values. Another data set is contained in “subjects.txt”. This file has the information on the individuals. Most important feature for us here are the "Age","sex" and "Race" columns. The "dbGap ID" column (second column) in this table should match the first row of the "metRmOlWithDbgapId.txt", and they represent the same individuals. Find all CpGs associated with Age but not with sex or Race, and display top 20 CpGs.

response:
```
# Read the metRmOlWithDbgapIdHeader.txt file
metRmOl <- read.table("metRmOlWithDbgapIdHeader.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# Read the subjects.txt file
subjects <- read.table("subjects.txt", header = TRUE, stringsAsFactors = FALSE, sep = "\t")

# Match the dbGap ID column in subjects table with the first row of metRmOl table
matched_ids <- intersect(colnames(metRmOl)[-1], subjects[,"dbGap ID"])

# Extract the rows of metRmOl dataset for matched ids
matched_metRmOl <- metRmOl[, c("CpG_id", matched_ids)]

# Filter the CpGs associated with Age but not with sex or Race
filtered_metRmOl <- matched_metRmOl[rowSums(subjects[subjects[,"dbGap ID"] %in% matched_ids, "Age"] != "") > 0 &
                                      rowSums(subjects[subjects[,"dbGap ID"] %in% matched_ids, "sex"] != "") == 0 &
                                      rowSums(subjects[subjects[,"dbGap ID"] %in% matched_ids, "Race"] != "") == 0, ]

# Display top 20 CpGs
top_20_CpGs <- head(filtered_metRmOl, 20)
top_20_CpGs
```
Note: Please make sure to replace "metRmOlWithDbgapIdHeader.txt" and "subjects.txt" with the actual file paths or the names of the files in the working directory.
